# -*- coding: utf-8 -*-
"""ASSIGNMENT-3-KNN_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bvIDtIRfrlXIvzjDYokS8HihP4D7rTdy
"""

from google.colab import drive
drive.mount('/content/drive')

import numpy as np
import pandas as pd

# dataset
realestate_dataset=pd.read_csv("/content/drive/MyDrive/AI/Real estate valuation data set(1).csv")

realestate_dataset.head(10)

realestate_dataset.isnull().any()

realestate_dataset.isnull().sum()

x=realestate_dataset.iloc[:,1:5].values
y=realestate_dataset.iloc[:,7:8].values

x

y

x.shape

y.shape

#split the data
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2,random_state=0)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

#feature selection
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

from sklearn.neighbors import KNeighborsRegressor
knn=KNeighborsRegressor()

knn.fit(x_train,y_train)

y_pred=knn.predict(x_test)

y_pred

from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

y_pred=knn.predict(sc.transform(([[2017.500,7.0,390.56840,10]])))
y_pred

